### ISSUE TITLE
Camera view

### ISSUE THREAD

**Issue by mvheun** [edwinvdpol/com.foscam#11]
I can change camera settings. But I don't have the actual view of the camera.....black screen.

**Comment by edwinvdpol** [comment]
You can adjust the settings in the app. If the screen is black, you have to change the settings. You can connect to the camera with another (ie. original Foscam) app? I think this issue is not related to the Homey Foscam app, but with the settings of the camera itself. Check out the [support section](https://foscam.com/faqs/index.html) of the Foscam support site.

**Comment by mvheun** [comment]
I have a clear view in the Foscam  app itself.  I will check further settings.

**Comment by edwinvdpol** [comment]
The Homey app just takes a snapshot from the camera, and processes this futher the way you would like (e-mail or Telegram etc.). If the snapshot itself is black, I really don't know what causes this, but is a camera issue. Sorry I can't be of more assistance. Good luck, and let me know if you find something 👍

**Comment by mvheun** [comment]
Ok thanks!

**Comment by edwinvdpol** [comment]
Closed due to inactivity.
